language: ruby
rvm:
  - ruby-head
  - 2.2-head
  - 2.1.1
  - 1.9.3
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.2-head

sudo: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y liblua5.1-dev
